server:
  port: 8020

#数据库连接相关配置
spring:
  application:
    name: menu
  database:
    name: orderingsystem
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ty123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:prefer-ip-address: true